// Contenido maestro de KAIRO — cursos, comunidad, consultoría y automatización.
// Fuente única: alimenta las páginas /curso/[slug] y el dashboard /cuenta.

export const PAQUETES = [
  {
    slug: "quickstart",
    nombre: "KAIRO Quickstart",
    precio: "$39",
    tipo: "curso",
    duracion: "1 hora · a tu ritmo",
    nivel: "Principiante absoluto",
    tagline: "Tu primer agente de IA funcionando en 1 hora — sin saber programar.",
    paraQuien: "Para el que sabe que tiene que usar IA pero no sabe por dónde empezar. Si nunca armaste nada con IA y querés un primer triunfo rápido, este es tu punto de partida.",
    promesa: "En menos de una hora salís con un agente de IA tuyo, funcionando, y con la confianza de que esto no es magia: es un proceso que podés repetir.",
    incluye: [
      "Video paso a paso (te muestro la pantalla, no teoría)",
      "Plantilla de agente lista para copiar y pegar",
      "Banco de 30 prompts probados para arrancar",
      "Checklist de '¿qué automatizo primero?'",
      "Acceso de por vida + actualizaciones",
    ],
    modulos: [
      { n: 1, titulo: "El clic mental", lecciones: ["Qué es (y qué NO es) un agente de IA", "Los 3 lugares donde la IA te da más retorno hoy"], resultado: "Entendés dónde aplicar IA sin marearte con mil herramientas." },
      { n: 2, titulo: "Armamos tu primer agente", lecciones: ["Elegir la herramienta correcta (gratis para empezar)", "Copiar la plantilla y adaptarla a vos", "La prueba: tu agente respondiendo solo"], resultado: "Tenés un agente real funcionando en tu pantalla." },
      { n: 3, titulo: "Que no se rompa", lecciones: ["Los 5 errores típicos del principiante", "Cómo mejorar las respuestas con buenos prompts", "Tu próximo paso"], resultado: "Sabés mantenerlo y mejorarlo solo." },
    ],
    resultados: [
      "Un agente de IA tuyo, funcionando",
      "La metodología para repetirlo con otra tarea",
      "Cero humo: entendés qué pasa por debajo",
    ],
    textoLargo: "La mayoría de la gente queda paralizada con la IA por la misma razón: hay demasiadas herramientas, demasiados gurús y demasiada teoría. Quickstart rompe esa parálisis con una sola cosa — un triunfo rápido y real. En lugar de explicarte cómo funciona un modelo de lenguaje por dentro, te siento frente a la pantalla y armamos juntos, paso a paso, tu primer agente de IA: algo que responde, que resuelve una tarea concreta tuya, y que podés mostrarle a alguien hoy mismo. La neurociencia del aprendizaje es clara: el primer logro temprano es lo que genera la dopamina que te hace volver. Por eso Quickstart está diseñado para que ganes en menos de una hora, no en semanas. Adentro vas a encontrar el video completo donde te muestro cada clic, la plantilla exacta que uso, un banco de 30 prompts que ya probé, y un checklist para decidir qué tarea conviene automatizar primero en tu caso. No necesitás tarjeta de crédito de ninguna herramienta cara ni saber una línea de código. Cuando termines, no solo vas a tener un agente: vas a tener la metodología para repetirlo con cualquier otra tarea de tu trabajo o tu negocio. Quickstart es la puerta de entrada a todo el universo KAIRO — el primer escalón de una escalera que llega hasta tener tu negocio entero corriendo con IA.",
    faq: [
      { q: "¿Necesito saber programar?", a: "No. Todo es con herramientas visuales y plantillas. Si sabés usar WhatsApp, podés con esto." },
      { q: "¿Cuánto tarda?", a: "Aproximadamente una hora. Podés pausar y seguir cuando quieras." },
      { q: "¿Sirve si ya sé algo de IA?", a: "Si ya armaste agentes, te conviene saltar directo a Foundations." },
    ],
    cta: { label: "Empezar por $39", tipo: "comprar", plan: "quickstart" },
    siguiente: "foundations",
  },
  {
    slug: "foundations",
    nombre: "KAIRO Foundations",
    precio: "$297",
    tipo: "curso",
    destacado: true,
    duracion: "6 módulos · ~6 semanas a tu ritmo",
    nivel: "De principiante a operador",
    tagline: "De cero a tu primer sistema de IA que te ahorra horas — o que factura.",
    paraQuien: "Para el que ya entendió que la IA sirve y quiere construir algo de verdad: un sistema que trabaje por él, ya sea para su propio negocio o para empezar a vender automatizaciones a otros.",
    promesa: "Salís con un sistema de IA completo funcionando de punta a punta, y con el criterio para diseñar el próximo solo. Es la base sobre la que se construye un negocio.",
    incluye: [
      "6 módulos en video, paso a paso",
      "Plantillas y blueprints de cada sistema que armamos",
      "Banco de prompts profesional (100+)",
      "Mapa de herramientas: qué usar para cada cosa",
      "Plantilla de propuesta para venderlo como servicio",
      "Acceso de por vida + actualizaciones",
    ],
    modulos: [
      { n: 1, titulo: "Fundamentos que importan", lecciones: ["Cómo 'piensa' la IA (lo justo para usarla bien)", "El lenguaje de los prompts: la habilidad que más rinde", "Tu mapa de oportunidades de automatización"], resultado: "Ves tu trabajo con ojos de automatizador." },
      { n: 2, titulo: "Tu primer sistema real", lecciones: ["Conectar herramientas sin código", "Disparadores, acciones y datos", "Tu primer flujo que corre solo"], resultado: "Tenés un sistema funcionando, no un experimento." },
      { n: 3, titulo: "Agentes que hablan como humanos", lecciones: ["Diseñar la personalidad del agente", "Que responda DMs, mails o WhatsApp", "Califica y deriva solo"], resultado: "Un agente que atiende por vos 24/7." },
      { n: 4, titulo: "Contenido en automático", lecciones: ["Generar imágenes y video con IA", "Pipeline de contenido que se publica solo", "Mantener tu voz y tu marca"], resultado: "Tu contenido sale sin que estés encima." },
      { n: 5, titulo: "Que no se caiga", lecciones: ["Manejo de errores y límites", "Costos, privacidad y supervisión humana", "Monitoreo: que te avise si algo falla"], resultado: "Un sistema confiable, no frágil." },
      { n: 6, titulo: "De sistema a negocio", lecciones: ["Empaquetar lo que armaste como servicio", "Ponerle precio sin regalar tu trabajo", "Tu primera propuesta a un cliente"], resultado: "Sabés cómo cobrar por esto." },
    ],
    resultados: [
      "Un sistema de IA completo, tuyo y funcionando",
      "El criterio para diseñar el próximo sin ayuda",
      "Una propuesta lista para venderle a tu primer cliente",
    ],
    textoLargo: "Foundations es el corazón de KAIRO. Si Quickstart te da el primer triunfo, Foundations te da el oficio. A lo largo de seis módulos construimos juntos — no en teoría, en tu pantalla — un sistema de IA completo: desde los fundamentos que de verdad importan (sin perderte en matemática que no vas a usar), hasta un agente que atiende clientes solo, un pipeline de contenido que se publica sin que estés encima, y la parte que casi nadie te enseña: cómo hacer que todo eso no se caiga. Cada módulo está pensado como un escalón de una transformación: empezás viendo tu trabajo como una lista de tareas manuales y terminás viéndolo como un conjunto de sistemas que pueden correr solos. Esa es la mentalidad que separa al que 'usa ChatGPT' del que construye negocios con IA. El módulo final es el que cambia vidas: tomamos lo que aprendiste a construir y te muestro cómo empaquetarlo como un servicio, ponerle precio sin regalarte, y armar tu primera propuesta para un cliente. Porque la verdad incómoda es esta: aprender IA no te cambia la vida; aprender a vender lo que hacés con IA, sí. Adentro vas a tener los seis módulos en video, los blueprints de cada sistema que armamos para que los copies, un banco de más de 100 prompts profesionales, el mapa de qué herramienta usar para cada cosa, y la plantilla de propuesta comercial. Foundations no es un curso para coleccionar; es la base sobre la que se para todo lo demás — la comunidad, el bootcamp y, si querés, tu propia agencia.",
    faq: [
      { q: "¿Y si nunca automaticé nada?", a: "Está pensado para arrancar de cero. Si querés un calentamiento previo, hacé Quickstart primero." },
      { q: "¿Las herramientas son caras?", a: "Trabajamos con opciones de bajo costo o gratis para empezar. Te muestro cómo escalar sin gastar de más." },
      { q: "¿Me sirve para conseguir clientes?", a: "Sí. El módulo 6 es justamente cómo empaquetar y vender lo que armás." },
      { q: "¿Tengo acceso para siempre?", a: "Sí, acceso de por vida y todas las actualizaciones futuras incluidas." },
    ],
    cta: { label: "Acceder por $297", tipo: "comprar", plan: "foundations" },
    siguiente: "comunidad",
  },
  {
    slug: "comunidad",
    nombre: "Comunidad KAIRO",
    precio: "$49/mes",
    tipo: "comunidad",
    duracion: "Suscripción mensual · cancelás cuando quieras",
    nivel: "Todos los niveles",
    tagline: "El lugar donde no te quedás solo: cursos, automatizaciones listas, comunidad y lives.",
    paraQuien: "Para el que quiere seguir creciendo con IA con apoyo constante, ideas frescas cada semana y gente que está en la misma. El que aprende mejor acompañado que solo.",
    promesa: "Cada mes salís con algo nuevo implementado, una duda resuelta y una idea que no se te hubiera ocurrido solo. La garantía de 90 días te cubre: si no te sirve, te devolvemos.",
    incluye: [
      "Todos los cursos KAIRO incluidos mientras seas miembro",
      "Biblioteca de automatizaciones listas para copiar",
      "Lives y Q&A en vivo (ES/EN)",
      "Comunidad privada para preguntar y compartir",
      "Plantillas y prompts nuevos cada semana",
      "Garantía de 90 días",
    ],
    modulos: [
      { n: 1, titulo: "Acceso total a cursos", lecciones: ["Quickstart, Foundations y todo lo nuevo", "Rutas de aprendizaje según tu objetivo"], resultado: "Aprendés a tu ritmo, sin pagar por separado." },
      { n: 2, titulo: "Biblioteca de automatizaciones", lecciones: ["Flujos listos para importar", "Agentes pre-armados para casos comunes"], resultado: "Copiás algo que ya funciona en vez de empezar de cero." },
      { n: 3, titulo: "Comunidad + lives", lecciones: ["Q&A en vivo cada semana", "Feedback de tus sistemas", "Networking con gente que está construyendo"], resultado: "Nunca te trabás solo." },
    ],
    resultados: [
      "Acceso a todo el conocimiento KAIRO en un solo lugar",
      "Implementás más rápido copiando lo que ya funciona",
      "Una red de gente que te empuja a seguir",
    ],
    textoLargo: "La razón número uno por la que la gente abandona la IA no es que sea difícil — es que la encara sola. Se traba en un error, no tiene a quién preguntarle, lo deja para 'cuando tenga tiempo', y nunca vuelve. La Comunidad KAIRO existe para que eso no te pase. Es una membresía mensual que te da tres cosas que solo no podés tener: acceso a todos los cursos de KAIRO mientras seas miembro (Quickstart, Foundations y todo lo que vaya saliendo), una biblioteca de automatizaciones y agentes ya armados que copiás e importás en minutos en vez de construir de cero, y lo más valioso — gente. Lives y sesiones de preguntas y respuestas cada semana donde traés tu sistema, mostrás dónde te trabaste y salís con la solución. La neurociencia de los hábitos lo confirma: lo que sostiene una conducta nueva no es la fuerza de voluntad, es el entorno. Rodearte de gente que está construyendo con IA hace que vos también construyas. Cada semana subimos plantillas y prompts nuevos, así que siempre tenés una excusa para volver y un próximo paso concreto. Y porque creemos en lo que ofrecemos, va con garantía de 90 días: si en tres meses sentís que no te movió la aguja, te devolvemos el dinero. La Comunidad es el lugar natural para quedarte después de Foundations — o para arrancar si lo que querés es no quedarte nunca solo en el camino.",
    faq: [
      { q: "¿Puedo cancelar cuando quiera?", a: "Sí, sin vueltas. Cancelás desde tu cuenta y listo." },
      { q: "¿Incluye los cursos o los pago aparte?", a: "Incluidos mientras seas miembro: Quickstart, Foundations y lo nuevo." },
      { q: "¿Y la garantía?", a: "90 días. Si no te sirve, te devolvemos el dinero, sin interrogatorio." },
    ],
    cta: { label: "Sumarme por $49/mes", tipo: "comprar", plan: "comunidad" },
    siguiente: "bootcamp",
  },
  {
    slug: "bootcamp",
    nombre: "KAIRO Bootcamp",
    precio: "$797",
    tipo: "curso",
    duracion: "Cohorte en vivo de 30 días",
    nivel: "Intermedio · implementación con acompañamiento",
    tagline: "30 días, en vivo, conmigo encima — salís con tu sistema implementado de verdad.",
    paraQuien: "Para el que no quiere otro curso que se queda a medias. El que necesita fecha, ritmo, acompañamiento y un poco de presión sana para terminar lo que empieza.",
    promesa: "En 30 días no 'viste' el contenido: lo implementaste. Salís con un sistema de IA funcionando en tu negocio y con la confianza de haberlo hecho acompañado.",
    incluye: [
      "Cohorte en vivo de 30 días (grupo reducido)",
      "Sesiones semanales en vivo + grabaciones",
      "Revisión de tu sistema en directo",
      "Todo el contenido de Foundations incluido",
      "Comunidad de tu cohorte (los que arrancan juntos)",
      "Certificado de finalización KAIRO",
    ],
    modulos: [
      { n: 1, titulo: "Semana 1 — Tu plan", lecciones: ["Diagnóstico de tu negocio", "Elegís el sistema que vas a construir", "Setup de herramientas"], resultado: "Salís con un plan claro y fecha." },
      { n: 2, titulo: "Semana 2 — Construís", lecciones: ["Armás tu primer flujo en vivo", "Revisión grupal", "Ajustes"], resultado: "Tu sistema empieza a tomar forma." },
      { n: 3, titulo: "Semana 3 — Agente + contenido", lecciones: ["Sumás un agente de atención", "Pipeline de contenido", "Pruebas reales"], resultado: "El sistema ya hace trabajo de verdad." },
      { n: 4, titulo: "Semana 4 — Lanzás", lecciones: ["Lo dejás funcionando y monitoreado", "Cómo escalarlo o venderlo", "Demo final de tu cohorte"], resultado: "Terminás con un sistema vivo y un plan de crecimiento." },
    ],
    resultados: [
      "Un sistema implementado de verdad en 30 días",
      "El hábito de construir con fechas y acompañamiento",
      "Certificado y una cohorte que te conoce",
    ],
    textoLargo: "Todos tenemos cursos comprados que nunca terminamos. No es por falta de ganas — es por falta de estructura. El Bootcamp KAIRO existe para resolver exactamente eso. Es una cohorte en vivo de 30 días donde no estás solo frente a una plataforma: estás conmigo y con un grupo reducido de gente que arranca el mismo día que vos. Hay fecha de inicio, hay ritmo semanal, hay sesiones en vivo donde traés tu sistema y lo revisamos en directo, y hay esa presión sana del grupo que hace que sí o sí avances. La diferencia entre un curso a tu ritmo y un bootcamp es la diferencia entre 'algún día lo hago' y 'lo hice en cuatro semanas'. La estructura está pensada como un sprint: la primera semana diagnosticamos tu negocio y elegís qué sistema vas a construir; la segunda lo armás; la tercera le sumás un agente de atención y un pipeline de contenido; y la cuarta lo dejás funcionando, monitoreado, y con un plan para escalarlo o venderlo. Incluye todo el contenido de Foundations como material de apoyo, las grabaciones de cada sesión por si te perdés alguna, la comunidad de tu cohorte, y un certificado de finalización. Es la opción para el que ya probó aprender solo y sabe que con acompañamiento llega. Si querés terminar lo que empezás y salir con algo real funcionando, el Bootcamp es tu camino.",
    faq: [
      { q: "¿Cuándo arranca la próxima cohorte?", a: "Abrimos cohortes por fecha. Dejá tu mail o escribime y te aviso la próxima." },
      { q: "¿Y si me pierdo una sesión en vivo?", a: "Todas quedan grabadas. Igual te recomiendo venir en vivo: ahí está el valor." },
      { q: "¿Necesito experiencia previa?", a: "Ayuda haber hecho Quickstart o Foundations, pero el Bootcamp arranca con un diagnóstico para nivelar." },
    ],
    cta: { label: "Reservar mi lugar — $797", tipo: "comprar", plan: "bootcamp" },
    siguiente: "founders-sprint",
  },
  {
    slug: "founders-sprint",
    nombre: "Founders Sprint 1-a-1",
    precio: "$1.500+",
    tipo: "consultoria",
    duracion: "30 o 90 días · 1-a-1 conmigo",
    nivel: "Para fundadores y negocios en marcha",
    tagline: "Consultoría personal: nos sentamos vos y yo y armamos la IA de tu negocio.",
    paraQuien: "Para el dueño de negocio o fundador que no quiere aprender a hacerlo — quiere que se haga, con criterio, mirando sus números y su contexto real.",
    promesa: "Trabajamos uno a uno sobre TU negocio. Salís con una estrategia de IA hecha a medida, sistemas priorizados por retorno, y el acompañamiento para implementarlos bien.",
    incluye: [
      "Diagnóstico profundo de tu negocio y procesos",
      "Hoja de ruta de IA priorizada por retorno",
      "Sesiones 1-a-1 (30 o 90 días según el plan)",
      "Diseño de tus sistemas y agentes clave",
      "Acompañamiento en la implementación",
      "Acceso directo conmigo por el período del sprint",
    ],
    proceso: [
      { paso: 1, titulo: "Diagnóstico", detalle: "Mapeamos tu negocio, tus procesos y dónde se te va el tiempo y la plata. Salimos con las oportunidades de IA ordenadas por retorno." },
      { paso: 2, titulo: "Estrategia", detalle: "Armo tu hoja de ruta: qué sistema primero, qué después, con qué herramientas y qué se puede esperar de cada uno." },
      { paso: 3, titulo: "Diseño + build", detalle: "Diseñamos y construimos tus sistemas y agentes clave, mirando tus casos reales, no ejemplos de manual." },
      { paso: 4, titulo: "Implementación + handoff", detalle: "Los dejamos funcionando, te enseño a operarlos y definimos cómo escalar. El conocimiento queda con vos." },
    ],
    resultados: [
      "Una estrategia de IA hecha para tu negocio, no genérica",
      "Sistemas clave diseñados y en marcha",
      "Criterio propio para seguir solo después del sprint",
    ],
    textoLargo: "Hay un punto en el que ya no necesitás otro curso — necesitás que alguien se siente con vos, mire tu negocio de verdad y te diga 'esto primero, esto después, así'. El Founders Sprint es eso. Es consultoría uno a uno, conmigo, durante 30 o 90 días, enfocada cien por ciento en tu negocio. No es contenido genérico: arrancamos con un diagnóstico profundo de tus procesos, dónde se te va el tiempo y la plata, y de ahí salgo con una hoja de ruta de IA priorizada por retorno — porque no todas las automatizaciones valen lo mismo, y empezar por la correcta es la mitad del juego. Después diseñamos y construimos juntos tus sistemas clave, mirando tus casos reales: tus clientes, tu operación, tu contexto. Y los dejamos funcionando, con un handoff donde te enseño a operarlos para que el conocimiento quede con vos y no dependas de nadie. Durante todo el sprint tenés acceso directo conmigo. Es la opción para el fundador que valora su tiempo, que prefiere comprar criterio antes que aprender a los golpes, y que quiere salir con algo construido y una dirección clara. El precio arranca en $1.500 y se define según el alcance — por eso el primer paso siempre es una charla para entender qué necesitás. Si querés saltarte la curva de aprendizaje y trabajar codo a codo, agendá y lo vemos.",
    faq: [
      { q: "¿Por qué el precio dice '$1.500+'?", a: "Porque depende del alcance (30 vs 90 días, cuántos sistemas). Lo cerramos después de una charla de diagnóstico." },
      { q: "¿Vos lo construís o me enseñás?", a: "Las dos cosas: construimos juntos y te dejo operándolo solo. El conocimiento queda con vos." },
      { q: "¿Cómo empiezo?", a: "Con una charla de diagnóstico sin compromiso. Ahí definimos alcance y precio." },
    ],
    cta: { label: "Agendar charla de diagnóstico", tipo: "agendar" },
    siguiente: "hecho-para-vos",
  },
  {
    slug: "hecho-para-vos",
    nombre: "Hecho para vos (Done for you)",
    precio: "A medida",
    tipo: "dfy",
    duracion: "Proyecto + retainer mensual",
    nivel: "Para negocios que quieren resultados, no aprender",
    tagline: "Vos seguí con lo tuyo. Nosotros construimos y mantenemos la IA de tu negocio.",
    paraQuien: "Para el negocio que no quiere ni aprender ni implementar — quiere que un equipo le construya las automatizaciones y los agentes, los deje funcionando y los mantenga.",
    promesa: "Nos das el problema, nosotros entregamos el sistema funcionando y lo mantenemos andando. Vos ves los resultados; nosotros nos ocupamos de que no se caiga.",
    incluye: [
      "Automatizaciones y agentes a medida",
      "Construcción de punta a punta (como hicimos con Ovo Flow)",
      "Integraciones con tus herramientas actuales",
      "Monitoreo y mantenimiento mensual (retainer)",
      "Soporte prioritario",
      "Reportes de resultados",
    ],
    proceso: [
      { paso: 1, titulo: "Diagnóstico y propuesta", detalle: "Entendemos tu operación y te mandamos una propuesta clara: qué construimos, en cuánto tiempo y qué resultado esperar." },
      { paso: 2, titulo: "Diseño del sistema", detalle: "Diseñamos la solución completa: agentes, automatizaciones e integraciones con lo que ya usás." },
      { paso: 3, titulo: "Construcción", detalle: "Lo construimos de punta a punta. Vos seguís con tu negocio; nosotros te mantenemos al tanto." },
      { paso: 4, titulo: "Lanzamiento", detalle: "Lo dejamos funcionando en tu operación, probado y monitoreado." },
      { paso: 5, titulo: "Mantenimiento (retainer)", detalle: "Nos quedamos para que no se caiga, lo mejoramos con el tiempo y te pasamos reportes de resultados." },
    ],
    resultados: [
      "Un sistema de IA a medida, funcionando en tu negocio",
      "Cero tiempo tuyo invertido en construirlo",
      "Un equipo que lo mantiene andando y lo mejora",
    ],
    textoLargo: "No todo el mundo quiere aprender a construir con IA — y está perfecto. Muchos negocios solo quieren el resultado: que los DMs se respondan solos, que el contenido salga sin esfuerzo, que los procesos repetitivos dejen de comerse horas. Para ellos existe 'Hecho para vos'. Es nuestro servicio de construcción a medida: nos contás el problema, diseñamos la solución, la construimos de punta a punta y la dejamos funcionando en tu operación — igual que hicimos con Ovo Flow, una plataforma completa de IA para negocios que armamos desde cero, con agente de atención 24/7, publicación automática de contenido, multi-cuenta y pagos integrados. La diferencia entre 'Hecho para vos' y contratar a un freelance suelto es el mantenimiento: los sistemas de IA no son un cuadro que colgás y listo; necesitan monitoreo, ajustes y mejoras. Por eso trabajamos con un retainer mensual: nos quedamos para que no se caiga, lo mejoramos con el tiempo y te pasamos reportes de resultados. El proceso es ordenado y sin sorpresas: diagnóstico y propuesta clara, diseño, construcción, lanzamiento y mantenimiento. El precio es a medida porque cada negocio es distinto — el primer paso siempre es una charla para entender qué necesitás y mandarte una propuesta concreta. Si querés los resultados de la IA sin tener que convertirte en experto, esto es para vos.",
    faq: [
      { q: "¿Cuánto cuesta?", a: "A medida, según el proyecto. Te mandamos una propuesta clara después de una charla de diagnóstico." },
      { q: "¿Qué es el retainer?", a: "Un fee mensual para mantener tus sistemas andando, mejorarlos y darte soporte. La IA necesita mantenimiento." },
      { q: "¿Tienen un caso real?", a: "Sí: Ovo Flow, una plataforma de IA para negocios que construimos de punta a punta. Te la mostramos en vivo." },
    ],
    cta: { label: "Hablemos de tu proyecto", tipo: "agendar" },
    siguiente: "quickstart",
  },
];

export function getPaquete(slug) {
  return PAQUETES.find((p) => p.slug === slug) || null;
}
